# Configure this Discovery Server
spring:
  application:
     name: EmployeeControllerRestClient
eureka:
  instance:
    hostname: http://localhost:8761/eureka/
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
     
server:
  port: 8761   # HTTP (Tomcat) port
